# Generated by Django 6.0.4 on 2026-05-11 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_replace_approval_with_report_approval_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timereportapprovaleventmodel",
            new_name="approvals_T_approva_d2cbdd_idx",
            old_name="approvals_E_approval_actioned_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportapprovalmodel",
            new_name="approvals_T_tenant__d0afe0_idx",
            old_name="approvals_T_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportapprovalmodel",
            new_name="approvals_T_tenant__b70bac_idx",
            old_name="approvals_T_tenant_created_idx",
        ),
    ]
