# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "approvals",
            "0004_rename_approvals_e_approval_actioned_idx_approvals_t_approva_d2cbdd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timereportapprovaleventmodel",
            options={
                "verbose_name": "Approval event",
                "verbose_name_plural": "Approval events",
            },
        ),
        migrations.AlterModelOptions(
            name="timereportapprovalmodel",
            options={
                "verbose_name": "Time report approval",
                "verbose_name_plural": "Time report approvals",
            },
        ),
    ]
