# Generated by Django 6.0.4 on 2026-04-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authz", "0002_authloginattemptmodel_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_departments",
            },
        ),
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("hired_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenants.tenantmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profiles",
                        to="authz.authusermodel",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_employees",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDepartmentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("left_reason", models.TextField(blank=True, default="")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="workforce.departmentmodel",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_assignments",
                        to="workforce.employeemodel",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_employee_departments",
            },
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_roles",
            },
        ),
        migrations.CreateModel(
            name="EmployeeRoleModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contract_hours_per_week", models.PositiveSmallIntegerField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("left_reason", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="workforce.employeemodel",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="workforce.rolemodel",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_employee_roles",
            },
        ),
        migrations.AddIndex(
            model_name="departmentmodel",
            index=models.Index(
                fields=["tenant", "name"], name="workforce_d_tenant__1aa1a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmodel",
            index=models.Index(
                fields=["is_active"], name="workforce_d_is_acti_eb6c17_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentmodel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_department_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="employeemodel",
            index=models.Index(
                fields=["tenant", "email"], name="workforce_e_tenant__b0f38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeemodel",
            index=models.Index(
                fields=["is_active"], name="workforce_e_is_acti_a162b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeemodel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "email"), name="unique_employee_email_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedepartmentmodel",
            index=models.Index(
                fields=["employee", "left_at"], name="workforce_e_employe_09838f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedepartmentmodel",
            index=models.Index(
                fields=["department"], name="workforce_e_departm_e02596_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeedepartmentmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("employee",),
                name="unique_active_employee_department",
            ),
        ),
        migrations.AddIndex(
            model_name="rolemodel",
            index=models.Index(
                fields=["tenant", "name"], name="workforce_r_tenant__b06ed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolemodel",
            index=models.Index(
                fields=["is_active"], name="workforce_r_is_acti_1c4502_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemodel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_role_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="employeerolemodel",
            index=models.Index(
                fields=["employee", "left_at"], name="workforce_e_employe_42727b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeerolemodel",
            index=models.Index(fields=["role"], name="workforce_e_role_id_2c4000_idx"),
        ),
        migrations.AddConstraint(
            model_name="employeerolemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("employee",),
                name="unique_active_employee_role",
            ),
        ),
    ]
