# Generated by Django 6.0.4 on 2026-04-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_created_by_updated_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='departmentmanagermodel',
            new_name='workforce_d_departm_140051_idx',
            old_name='workforce_d_dept_left_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentmanagermodel',
            new_name='workforce_d_employe_b086b6_idx',
            old_name='workforce_d_manager_emp_idx',
        ),
    ]
