# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workforce", "0006_role_role_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentmanagermodel",
            options={
                "verbose_name": "Department manager",
                "verbose_name_plural": "Department managers",
            },
        ),
        migrations.AlterModelOptions(
            name="departmentmodel",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="employeedepartmentmodel",
            options={
                "verbose_name": "Employee — department assignment",
                "verbose_name_plural": "Employee — department assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="employeemodel",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterModelOptions(
            name="employeerolemodel",
            options={
                "verbose_name": "Employee — role assignment",
                "verbose_name_plural": "Employee — role assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="rolemodel",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
    ]
