services:
  db:
    ports:
      - "5432:5432"

  backend:
    command: >
      sh -c "uv run python manage.py migrate --no-input &&
             uv run python manage.py collectstatic --no-input &&
             uv run uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    ports:
      - "3000:3000"
