# Generated by Django 6.0.4 on 2026-04-22 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timekeeping", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="periodmodel",
            new_name="timekeeping_tenant__4b3396_idx",
            old_name="timekeeping_period_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="periodmodel",
            new_name="timekeeping_tenant__82fbef_idx",
            old_name="timekeeping_period_dates_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentrychangehistorymodel",
            new_name="timekeeping_entry_i_50177a_idx",
            old_name="timekeeping_entry_change_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentrymodel",
            new_name="timekeeping_report__89f438_idx",
            old_name="timekeeping_entry_report_date_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportmodel",
            new_name="timekeeping_tenant__473d20_idx",
            old_name="timekeeping_report_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportmodel",
            new_name="timekeeping_employe_c60b4d_idx",
            old_name="timekeeping_report_emp_period_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportmodel",
            new_name="timekeeping_period__bca6c6_idx",
            old_name="timekeeping_report_period_status_idx",
        ),
        migrations.RenameIndex(
            model_name="timereportstatushistorymodel",
            new_name="timekeeping_report__728d2b_idx",
            old_name="timekeeping_status_hist_idx",
        ),
    ]
