# Generated by Django 6.0.4 on 2026-04-23 16:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0003_timeentry_hours_range_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='periodmodel',
            new_name='timekeeping_tenant__2dd9e7_idx',
            old_name='timekeeping_tenant__4b3396_idx',
        ),
        migrations.RenameIndex(
            model_name='periodmodel',
            new_name='timekeeping_tenant__f41d73_idx',
            old_name='timekeeping_tenant__82fbef_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentrychangehistorymodel',
            new_name='timekeeping_entry_i_a9ef7d_idx',
            old_name='timekeeping_entry_i_50177a_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentrymodel',
            new_name='timekeeping_report__c00b49_idx',
            old_name='timekeeping_report__89f438_idx',
        ),
        migrations.RenameIndex(
            model_name='timereportmodel',
            new_name='timekeeping_tenant__c4a661_idx',
            old_name='timekeeping_tenant__473d20_idx',
        ),
        migrations.RenameIndex(
            model_name='timereportmodel',
            new_name='timekeeping_employe_754db2_idx',
            old_name='timekeeping_employe_c60b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='timereportmodel',
            new_name='timekeeping_period__340316_idx',
            old_name='timekeeping_period__bca6c6_idx',
        ),
        migrations.RenameIndex(
            model_name='timereportstatushistorymodel',
            new_name='timekeeping_report__b71ea7_idx',
            old_name='timekeeping_report__728d2b_idx',
        ),
        migrations.AlterField(
            model_name='timeentrymodel',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24'))]),
        ),
        migrations.AlterModelTable(
            name='periodmodel',
            table='timekeeping_Period',
        ),
        migrations.AlterModelTable(
            name='timeentrychangehistorymodel',
            table='timekeeping_TimeEntryChangeHistory',
        ),
        migrations.AlterModelTable(
            name='timeentrymodel',
            table='timekeeping_TimeEntry',
        ),
        migrations.AlterModelTable(
            name='timereportmodel',
            table='timekeeping_TimeReport',
        ),
        migrations.AlterModelTable(
            name='timereportstatushistorymodel',
            table='timekeeping_TimeReportStatusHistory',
        ),
    ]
