# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "timekeeping",
            "0004_rename_timekeeping_tenant__4b3396_idx_timekeeping_tenant__2dd9e7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodmodel",
            options={"verbose_name": "Period", "verbose_name_plural": "Periods"},
        ),
        migrations.AlterModelOptions(
            name="timeentrychangehistorymodel",
            options={
                "verbose_name": "Time entry change history",
                "verbose_name_plural": "Time entry change history",
            },
        ),
        migrations.AlterModelOptions(
            name="timeentrymodel",
            options={
                "verbose_name": "Time entry",
                "verbose_name_plural": "Time entries",
            },
        ),
        migrations.AlterModelOptions(
            name="timereportmodel",
            options={
                "verbose_name": "Time report",
                "verbose_name_plural": "Time reports",
            },
        ),
        migrations.AlterModelOptions(
            name="timereportstatushistorymodel",
            options={
                "verbose_name": "Time report status history",
                "verbose_name_plural": "Time report status history",
            },
        ),
    ]
