# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costcalculationmodel",
            options={
                "verbose_name": "Cost calculation",
                "verbose_name_plural": "Cost calculations",
            },
        ),
        migrations.AlterModelOptions(
            name="overtimerulemodel",
            options={
                "verbose_name": "Overtime rule",
                "verbose_name_plural": "Overtime rules",
            },
        ),
        migrations.AlterModelOptions(
            name="ruleconditionmodel",
            options={
                "verbose_name": "Rule condition",
                "verbose_name_plural": "Rule conditions",
            },
        ),
    ]
