# Generated by Django 6.0.4 on 2026-04-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authz", "0002_authloginattemptmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("vat", models.IntegerField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tenants",
                        to="authz.authusermodel",
                    ),
                ),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="TenantMembershipModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("creator", "Creator"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("left_reason", models.TextField(blank=True, default="")),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to="authz.authusermodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to="authz.authusermodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_memberships",
            },
        ),
        migrations.AddIndex(
            model_name="tenantmodel",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantmodel",
            index=models.Index(fields=["is_active"], name="tenants_is_acti_ec1713_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantmodel",
            index=models.Index(fields=["vat"], name="tenants_vat_31b695_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantmembershipmodel",
            index=models.Index(
                fields=["tenant", "user"], name="tenant_memb_tenant__8fff4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembershipmodel",
            index=models.Index(
                fields=["tenant", "role"], name="tenant_memb_tenant__9ab271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembershipmodel",
            index=models.Index(
                fields=["left_at"], name="tenant_memb_left_at_413aac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembershipmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("tenant", "user"),
                name="unique_active_tenant_membership",
            ),
        ),
    ]
