# Generated by Django 6.0.5 on 2026-05-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenants",
            "0002_rename_tenant_memb_tenant__8fff4e_idx_tenants_ten_tenant__322a4c_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfileModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "workspace_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                (
                    "timezone",
                    models.CharField(blank=True, default="UTC", max_length=64),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("fiscal_year_start", models.CharField(default="01-01", max_length=5)),
                ("vat_number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "default_locale",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_profile",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_OrganizationProfile",
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="tenants_Org_tenant__a5be80_idx"
                    )
                ],
            },
        ),
    ]
