# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_drop_org_profile_unused_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationprofilemodel",
            options={
                "verbose_name": "Organisation profile",
                "verbose_name_plural": "Organisation profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantmembershipmodel",
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantmodel",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
    ]
