# Generated by Django 6.0.5 on 2026-05-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "authz",
            "0003_rename_authz_authl_user_id_occurr_idx_authz_authl_user_id_2542a1_idx_and_more",
        ),
        (
            "tenants",
            "0002_rename_tenant_memb_tenant__8fff4e_idx_tenants_ten_tenant__322a4c_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEventModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.BigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="authz.authusermodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "db_table": "audit_AuditEvent",
                "indexes": [
                    models.Index(
                        fields=["tenant", "occurred_at"],
                        name="audit_Audit_tenant__e6137a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action"],
                        name="audit_Audit_tenant__c14f0b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "resource_type", "resource_id"],
                        name="audit_Audit_tenant__072642_idx",
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"],
                        name="audit_Audit_actor_i_e55736_idx",
                    ),
                ],
            },
        ),
    ]
