# Generated by Django 6.0.5 on 2026-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        (
            "authz",
            "0003_rename_authz_authl_user_id_occurr_idx_authz_authl_user_id_2542a1_idx_and_more",
        ),
        (
            "tenants",
            "0002_rename_tenant_memb_tenant__8fff4e_idx_tenants_ten_tenant__322a4c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auditeventmodel",
            name="outcome",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="auditeventmodel",
            index=models.Index(
                fields=["tenant", "outcome"], name="audit_Audit_tenant__1fd420_idx"
            ),
        ),
    ]
