# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_auditeventmodel_outcome_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditeventmodel",
            options={
                "verbose_name": "Audit event",
                "verbose_name_plural": "Audit events",
            },
        ),
    ]
