# Generated by Django 6.0.4 on 2026-04-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authtokenmodel',
            new_name='authz_token_expires_bc05cf_idx',
            old_name='authz_tokens_expires_3d419f_idx',
        ),
        migrations.RenameIndex(
            model_name='authtokenmodel',
            new_name='authz_token_revoked_be88c3_idx',
            old_name='authz_tokens_revoked_2e4df6_idx',
        ),
        migrations.RenameIndex(
            model_name='authusermodel',
            new_name='authz_users_email_81ee10_idx',
            old_name='authz_users_email_bec237_idx',
        ),
        migrations.RenameIndex(
            model_name='authusermodel',
            new_name='authz_users_is_acti_f34988_idx',
            old_name='authz_users_is_acti_594997_idx',
        ),
    ]
