# Generated by Django 6.0.4 on 2026-05-04 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0002_auth_hardening"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="authlogineventmodel",
            new_name="authz_AuthL_user_id_2542a1_idx",
            old_name="authz_AuthL_user_id_occurr_idx",
        ),
        migrations.RenameIndex(
            model_name="authlogineventmodel",
            new_name="authz_AuthL_email_48e8fc_idx",
            old_name="authz_AuthL_email_o_occurr_idx",
        ),
        migrations.RenameIndex(
            model_name="authlogineventmodel",
            new_name="authz_AuthL_event_t_e5fb39_idx",
            old_name="authz_AuthL_event_t_occurr_idx",
        ),
        migrations.RenameIndex(
            model_name="authtokenmodel",
            new_name="authz_AuthT_user_id_c3458c_idx",
            old_name="authz_AuthT_user_id_revoke_idx",
        ),
    ]
