# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authz",
            "0003_rename_authz_authl_user_id_occurr_idx_authz_authl_user_id_2542a1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authloginattemptmodel",
            options={
                "verbose_name": "Login attempt",
                "verbose_name_plural": "Login attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="authlogineventmodel",
            options={
                "verbose_name": "Login event",
                "verbose_name_plural": "Login events",
            },
        ),
        migrations.AlterModelOptions(
            name="authtokenmodel",
            options={
                "verbose_name": "Refresh token",
                "verbose_name_plural": "Refresh tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="authusermodel",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
