# Generated by Django 6.0.5 on 2026-05-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0004_alter_authloginattemptmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authusermodel",
            name="timezone",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
