# Generated by Django 6.0.5 on 2026-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0005_authusermodel_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="authusermodel",
            name="tour_completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
